services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: docker_psql_golang
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD

volumes:
  db-data:
